plugins {
    // Can not use libraries.kotlin.version here per https://stackoverflow.com/questions/37555196/in-gradle-how-to-use-a-variable-for-a-plugin-version
    id 'org.jetbrains.kotlin.jvm' version '1.5.0'
    id 'java'
}

description = "Kotlin tests for Mockito."

apply from: "$rootDir/gradle/dependencies.gradle"

dependencies {
    testImplementation project(":")
    testImplementation libraries.junit4

    testImplementation libraries.kotlin.stdlib
    testImplementation libraries.kotlin.coroutines
}
