description = "Mockito JUnit 5 support"

apply from: "$rootDir/gradle/java-library.gradle"

dependencies {
    implementation project.rootProject
    implementation libraries.junitJupiterApi
    testImplementation libraries.assertj
    testImplementation libraries.junitPlatformLauncher
    testImplementation libraries.junitJupiterEngine
}

tasks.withType(Test) {
    useJUnitPlatform()
}
